# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24383b722279f033ea5b1906617dcf9de6da3e7fd5c20f6878a36e81bd6b433f0e06e81d42bd02c2ae97e1377f70f1be8f6201d8b6b61c006355866df85f8942

test:
  secret_key_base: cc20ab4c4fe7095926078f02052a844e366c10eb8d3ba16dc9daebdbba4b245abee07d6998e86d6da5b0444279628d7ef6308aa72ead5f850c46bed2bf720f28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
